- name: Declare a variable and access at play level
  connection: local
  become: yes
  vars:
    url: chandupcs.online
  tasks:
    - name: access a variable from play level
      ansible.builtin.debug:
       msg: URL == {{url}}