- name: Declare a variable and access at play level
  hosts: all
  become: yes
  vars:
    url: chandupcs.online
  tasks:
    - name: access a variable from play level
      ansible.builtin.debug:
       msg: URL == {{url}}



- name: Declare a variable and access at tasks level
  hosts: all
  become: yes
  tasks:
    - name: access a variable from tasks level
      ansible.builtin.debug:
        msg: URL == {{url}}
      vars:
        url: chandupcs.com


- name: Declare a variable and access at command level
  hosts: all
  become: yes
  tasks:
    - name: access a variable from command level
      ansible.builtin.debug:
        msg: URL == {{person}}
